services:
  - type: web
    name: kumunger-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PEPPER
        sync: false
      - key: FRONTEND_URL
        sync: false
